# Generated by Django 3.2.9 on 2021-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_alter_meetup_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(related_name='partcipant_name', to='meetup.Participant'),
        ),
    ]
